### PR TITLE
bem-forum: In the edit form cancel-button does not work

### PR DESCRIPTION
**Pull request by gela-d**

### CODE REVIEW

**Comment by gela-d** [comment]
@tavriaforever

**Comment by tavriaforever** [comment]
Can you explain me, why it did not work. I am try to fix it several times and and each time a could not found the solution.

**Comment by tadatuta** [comment]
@tavriaforever [here](https://github.com/bem/bem-forum/blob/BEMINFO-701/desktop.blocks/forum-form/forum-form.js#L63-L65) you bind to event on `button` but then [wait for it](https://github.com/bem/bem-forum/blob/BEMINFO-701/desktop.blocks/forum-form/forum-form.js#L199-L203) on `forum-form`.

**Comment by gela-d** [comment]
Пока что закрываю, там подумать надо как правильно сделать.

**Pull request closed without merging**
