### PR TITLE
Remove secure github token, change default locale

### PR DESCRIPTION
**Pull request by tavriaforever**
// cc @gela-d 
For default, user can do 60 request to github. If he want continue work with forum, he must add token.

### CODE REVIEW

**Comment by gela-d** [comment]
PR does'n work :( 
Server stated, no errors, but in browser "Server doesn't found"

**Comment by tadatuta** [comment]
offtopick
Server doesn't found -> Server not found

**Comment by gela-d** [comment]
Server ne najden :)

PS: thanks

**Comment by qfox** [comment]
> Server ne najden :)

:+1: lol

**Comment by tavriaforever** [comment]
Update

**Comment by gela-d** [comment]
Визуально - все хорошо. Запустила со своим токеном.

**Pull request merged**
