### PR TITLE
Big images break down page in Fx

### PR DESCRIPTION
**Pull request by gela-d**

### CODE REVIEW

**Comment by gela-d** [comment]
@tavriaforever

**Comment by tadatuta** [comment]
won't it be better to use something like

``` css
.img
{
    max-width: 100%;
}
```

?

**Comment by gela-d** [comment]
> won't it be better to use something like

He-he-he :) It's too easy :) We have this style https://github.com/bem/bem-forum/blob/master/desktop.blocks/issue/__body/issue__body.styl#L12
In reality, in flex-case, it works only in chrome.

**Comment by tavriaforever** [comment]
I propose to merge this fix, and separately, when will be do the project forum, more time to think over the decision, perhaps more deeper

**Pull request merged**
